### PR TITLE
Feature: Simple locale settings

### PR DESCRIPTION
**Pull request by johnie**
This feature adds possibility to add translated [default emotions](src/emotions/locale/sv/DefaultEmotions.ts) (in this case 🇸🇪 Swedish) but defaults to 🇬🇧  English. 

Would appreciate feedback, because the implementation could really be improved.

### Todo
- [ ] Translate title as well
- [ ] Use moment to define default locale

### CODE REVIEW

**Comment by dartungar** [comment]
@johnie hey, cool idea! The principal question I have is - why translate, and not just paste your own list of emotions in whatever language you prefer, via the settings? Do you feel that having default set of emotions in different languages is more convenient?
This is not a trick question, just curious about different use cases!

**Comment by manuel-cerezo** [comment]
Hey! 

Not pretending to answer in the name of @johnie but I find it quite interesting to add this feature as some people don't use Obsidian in English and it could be quite stressful for them to add their own emotions; so giving them the option of selecting the language they want will simplify that step and keep your plugin simple as you mentioned on #12

**Comment by dartungar** [comment]
@manueldevjour this makes sense - I was afraid it will lead to deviation from simplicity but after testing it I was convinced otherwise.

**Comment by manuel-cerezo** [comment]
I'll add on the next days a new PR to add Spanish also :) 

Thanks both of you for the work 😁

**Pull request merged**
